package de.mortis.player.types;

public enum PlayerAttributes {
    HEALTH, DEFENSE, SPEED, STRENGTH, MANA, CRIT_CHANCE, CRIT_DAMAGE, BONUS_ATTACK_SPEED, ABILITY_DAMAGE, MAGIC_FIND, PET_LUCK, TRUE_DEFENSE, SEA_CREATURE_CHANCE, FEROCITY, MINING_SPEED, MINING_FORTUNE, FARMING_FORTUNE, FORAGING_FORTUNE, FISHING_SPEED, HEALTH_REGEN, VITALITY, SWING_RANGE;
}
